name: Release CI
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ⚙ 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: 🏗 准备 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 🗳 安装依赖
        run: pnpm install

      - name: 📦 构建 npm 包
        run: pnpm run build

      # monorepo 发布时需关闭 workspaces-update，避免 npm version/publish 联动更新 workspace 依赖树报错
      # Refs: https://github.com/dhoulb/multi-semantic-release#npm-v85-npm-err-notarget-no-matching-version-found-for
      - name: 🚀 npm 包发布
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
